apiVersion: cassandra.datastax.com/v1beta1
kind: CassandraDatacenter
metadata:
  name: dc1
  namespace: cross-az
spec:
  clusterName: teads
  serverType: cassandra
  serverVersion: "3.11.7"
  allowMultipleNodesPerWorker: true
  size: 3
  racks:
    - name: az1
    - name: az2
    - name: az3
  config:    
    cassandra-yaml:
      authenticator: org.apache.cassandra.auth.PasswordAuthenticator
      authorizer: org.apache.cassandra.auth.CassandraAuthorizer
      role_manager: org.apache.cassandra.auth.CassandraRoleManager
    jvm-options:
      initial_heap_size: "200M"
      max_heap_size: "200M"
      additional-jvm-opts:
        - "-Ddse.system_distributed_replication_dc_names=dc1"
  storageConfig:
    cassandraDataVolumeClaimSpec:
      storageClassName: local-path
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 2Gi
  resources:
    requests:
      memory: 1Gi
      cpu: 1000m
    limits:
      memory: 1Gi
      cpu: 1000m
